### ISSUE TITLE
where is the source code?

### ISSUE THREAD

**Issue by ericogr** [apreb/eNode#1]

**Comment by apreb** [comment]
At this moment it's not yet available to publish, sorry.

**Comment by roblad** [comment]
Hi,


Do you plan to update source code ?

**Comment by apreb** [comment]
The code is a mix of simple examples found on the arduino sketch examples, there are no secret ingredients since i'm not a professional programmer.  I'm not publishing the code now because i need time to make it presentable to the public and right now it's not a priority and don't have the time to do that. More important the main purpose is to enable people to build their own affordable energy meters so having the source is kind of irrelevant. Sorry!

**Comment by roblad** [comment]
Hi,

there is a question what does mean Measure Direction Hack?
Could you put some jpg with interface and the question is that mqtt topic has 3 x voltage 3 x current and 3 x power ?

**Comment by apreb** [comment]
> there is a question what does mean Measure Direction Hack?

PZEM is unable to detect the direction of energy, this is important for grid-tie solar systems than export energy to the main grid when there is no local consumption. However the pzem chip provides a pin that toggles every time the offset between V and I is > 180º. The hack consists of connecting that pin into one of the ESP12 GPIO safely.


> Could you put some jpg with interface ?

Pics are already on the main page, the schematics and several detaled photos of actual builds. It is not easy but it's doable. There is a way to avoid the need of this hack by measuring the house consumption without the solar contribuition. 

> What is R17 and R15 - what I need to do with them ?

ESP12 is 3v3 and PZEM is 5V. You need to adjust the resistor of the optocoupler.
For the R15, only one should be present in a multi-PZEM scenario. If you are joining more PZEMs please remove the R15 from all PZEMs execpt the first one.

regarding the additional relays, one is enough for the majority of the cases, if you need more please use  dedicated hardware.

**Comment by roblad** [comment]
Hi,

1)
Thanks for explanation of resistors, but I do not understand, which one I need to keep wchich I need remove, could you put some schema or jpg haw it looks like exactly ? I need do the same schema as you have but you have showed schema but with not clear modification of resistors :-( . I guess that I need remove 2 R15 from 2 PZEMs and I should keep R15 on 1 of them. 
2)
"GPIO as switches and relays as it is in tasmota project, I need 3 imput GPIO as switches on/off for tank level with sending values as on/off S1 S2 S3 or even 2 switches enough."

Could you prepare bin with availability of add result for switch1 switch2 and switch3 assigned to GPIOs, it will bi nice when status of them could be sent on MQTT message as it is in TASMOTA :-), I do not need additional relays I would like to ask you about the switches only onn/off with the result of status in MQTT, could you ?

Thanks,
RL

**Comment by apreb** [comment]
OK, locate R15 and R17 on the following picture:

![](https://lh3.googleusercontent.com/CTNM1kgsoTB14Bke1T1xfXT-re9IOYt8y7QmMvYrVw2L4ApbTnllceUqCwd3P5Crkk2pfaWWi1m7eB2-aMY6KRCVKRPRS7v79FG_mz-ChTO7GjS8dZSvj5nW_3tIYS7eR-g8S5TwjDmaAYpQAT6LrQI4v1-uWeNiOyinLLyouBC9Eehx2DmTKvd-G7Gj9n1Eu1Jdx0ltMhiW8lFhQtxBQf1ACwFrwkYJ9DynmPsnuH7iKZNyR0id6DHH2XUAP9WnCcoN7ugq-8Z7kOUd8f4DnVE9U13WVTXAQT8MmTEbeLtuSgtrdQwzXTeJNYzapaqSQA-8hjghSRxJhygO1H8SyKHAHFKJgWDK6Jg3SabQ55UjLQF8pJSBr6-IEHPvML8_iw6jPfEKUbxa_f9QNeNx1pC10Tle4DjSJtuU0pmyI5JMrdfLAHgu7huAWg17PBW2iz2X9H9TE0G8lJw7HDCku6XTfchkcC5EWnWO4UrWkEi6_rWTz9BLvGBjfuO7DZbQWsBBGymjq_khh0q0Nn9x2MpLHIZxtKrbuO1N19i_YWQfOUhfIowZyuobq_2kBISxW7yTC_O7L059gCxsS_uE1CILEz_nl7zz71rBakkfn4YG4l5KIMqeA3iO80sE0HneI6_8yCc_jM4ggNrhWYuMi52yLs30-mtw=w1199-h908-no)

Make sure all PZEMs have the following Resistor configuration:

PZEM1:
R17 = 510 OHM
R15 = Leave the resistor as is

PZEM2:
R17 = 510 OHM
R15 = Remove the resistor

PZEM3:
R17 = 510 OHM
R15 = Remove the resistor

I hope it is clear now.

**Comment by roblad** [comment]
Hi,


Yest, Thanks, what about second question ?

Regardss,
RL

**Comment by gntec97** [comment]
Hello please help with the three phase power meter code. I use a single Pzem-004 with serial port and works fine, but i am missing for build the three phase meter with ESP module. My email Is gncorallo@gmail.com

**Comment by roblad** [comment]
Hi,


I am still waiting for modules

Rgds,
RL

**Comment by apreb** [comment]
Roblad im using the gpios for other functions your request wont happen im sorry.

Gntec97, you have to be more specific than that, please open a neu issue since this one is very offtopic. I'm closing this now.

Regards,
