### ISSUE TITLE
Additional details

### ISSUE THREAD

**Issue by nferreyra** [apreb/eNode#3]
Hi, 

Nice project you have here. I've recently heard about this modules and I was trying to replace my hand-made energy monitor (openenergymonitor based) with a compact and wireless version like the one you have here.
Would you mind share additional details like how you are feeding the WeMos on the box you show as "Single energy meter with energy direction"? Is the current draw from the WeMos within the range PZEM can supply to have it working?
On the "Xtreme edition" I see an external PSU. What's the diference there?
Do you have the schematics or some support material you can share from the PZEM-004T?

Thank you

**Comment by apreb** [comment]
Hi, thank you.

On my initial attempts i tried to power the ESP8266 directly from the PZEM supply but i could not make it work, so i just added a external PSU.

The builds are all based on the schematic, all you need to do is to power the ESP8266 from a external PSU and connect the serial port between them, making sure have the correct resistors to match the different operating voltage between PZEM and ESP8266.

The "Single energy meter with energy direction" has the PSU hidden on the bottom of the box ;-)

The Xtreme edition ilustrates the most compact form, removes the isolation between the mains and the chip and also uses the bare ESP8266 with the minimal circuit to make it stable.

**Comment by nferreyra** [comment]
Thanks for your answer.
